# This is a Docker Compose file to work with Loud ML and an InfluxDB stack.

version: "2"

services:
  app:
    build: app
    ports:
      - "8080:8080"

  client:
    build: client
    depends_on:
      - app

  controller:
    build: controller
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./log:/var/log
    ports:
      - "8079:8079"

  loudml:
    image: loudml/community
    volumes:
      - ./loudml/loudml.yml:/etc/loudml/config.yml:ro
      - ./var/loudml:/var/lib/loudml
    ports:
      - "8077:8077"
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./var/influxdb:/var/lib/influxdb

  chronograf:
    image: loudml/chronograf
    depends_on:
      - influxdb
      - loudml
      - kapacitor
    ports:
      - "8888:8888"
    volumes:
      - ./var/chronograf:/var/lib/chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
      LOUDML_URL: http://loudml:8077
      KAPACITOR_URL: http://kapacitor:9092

  kapacitor:
    image: kapacitor:latest
    depends_on:
      - controller
      - influxdb
    volumes:
      - ./kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - ./var/kapacitor:/var/lib/kapacitor
    environment:
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086

  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./log:/var/log/app:ro
    depends_on:
      - controller
      - influxdb
    environment:
      INFLUXDB_URL: http://influxdb:8086
